name: UNDrugs
version: "${project.version}"
main: unmineraft.undrugs.UNDrugs
api-version: 1.18
authors: [ColchasGOD]
description: Manejo de items especiales para el servidor de Minecraft UN
website: https://github.com/UN-Minecraft

commands:
  drugs:
    description: Método de obtención de los items de tipo droga
    permission: op
  undrugs:
    description: Comando administrador del plugin
    permission: op
